const questions = ["what is your idea of perfect happiness?",
"what is your greatest fear?",
"who are your heroes in real life?",
"what is the trait you most deplore in yourself?",
"what is the trait you most deplore in others?",
"what is your favorite journey?",
"what do you consider the most overrated virtue?",
"which word or phrases do you most overuse?",
"what is your greatest regret?",
"what is your current state of mind?",
"if you could change one thing about your family, what would it be?",
"what is your most treasured possession?",
"what do you regard as the lowest depth of misery?",
"where would you like to live?",
"what is your favorite occupation?",
"what is the quality you most like in a man?",
"what is the quality you most like in a woman?",
"what are your favorite names?",
"what is your motto?",
"what is your greatest extravagance?",
"on what occasion do you lie?",
"what do you most dislike about your appearance?",
"which living person do you most despise?",
"which words or phrases do you most overuse?",
"what or who is the greatest love of your life?",
"when and where were you happiest?",
"which talent would you most like to have?",
"if you could change one thing about yourself, what would it be?",
"what do you consider your greatest achievement?",
"if you were to die and come back as a person or a thing, what would it be?",
"where would you most like to live?",
"what is your most marked characteristic?",
"what do you most value in your friends?",
"who are your favorite writers?",
"who are your favorite musicians?",
"who is your hero of fiction?",
"which historical figure do you most identify with?",
"what is it that you most dislike?",
"how would you like to die?",
"what was the last movie you watched?",
"can you name the last three movies you watched? ",
"what was the last thing you really laughed about?",
"when was the last time you felt exactly how you feel right now?",
"can you name the last 5 meals you’ve eaten?",
"who was the most interesting person in your school?",
"who is the worst leader you know?",
"who is the best leader you know?",
"who is the the best teacher you have ever had?",
"can you remember all the words to your favourite childhood nursery rhyme?",
"what is the best kiss you’ve ever had?",
"what is your favourite quote?",
"what is your favourite beverage? why?",
"what is your favourite TV or movie quote?",
"if you could die tomorrow, what would you do today?",
"if you had to pick any day in your life to relive, which would it be?",
"is there anyone from your childhood that you would go back and be friends with?",
"what is the most spiritual you have ever felt?",
"what makes you feel alive?",
"what makes you feel small?",
"what behaviour in others annoys you the most?",
"what behaviour in yourself annoys you the most?",
"what phenomenon is the most frustrating to you?",
"what would your last meal request be?",
"how would you spend your last night on earth?",
"given infinite time, how would you spend this next hour?",
"given infinite time, how would you spend tomorrow?",
"given infinite time, how would you spend today?",
"what is your understanding of love?",
"do you think you know love?",
"what is your greatest fear?",
"when do you feel most vulnerable?",
"what is the meanest thing you have ever done?",
"what is the worst thing you’ve ever told yourself?",
"what is the best lie you’ve ever told?",
"if you could be rid of one of your habits, which would it be?",
"if you could gain a habit, what would it be?",
"which time in history excites you the most?",
"do you ever feel you should have been born in a different time? when?",
"do you ever feel you should have been born in a different place? where?",
"if you’d had the choice, would you have picked your parents?",
"who would you switch places with?",
"what makes you feel alone?",
"what makes you feel alive?",
"what makes you cry?",
"what is the deepest emotion you have ever felt?",
"what is the strongest longing you have ever felt?",
"do you remember the first time something didn’t go your way?",
"what is your first recollection of something not going your way?",
"what is your first recollection of winning?",
"how do you like to be active?",
"how do you like to rest?",
"what is your biggest extravagance?",
"what is one thing you wish you weren’t deprived of as a child?",
"what is one thing you wish you had?",
"what is your favourite game?",
"what is your happiest memory?",
"when do you feel sorry for yourself?",
"if you could talk to anyone living, right now, who would it be?",
"are you being true to yourself right now?",
"when is a time that someone broke your trust?",
"who do you miss right now?",
"what day of your life would you relive if you could?",
"what day of your life would you redo if you could?",
"when did you first feel loved?",
"when have you been most afraid?",
"what excites you most about the future?",
"what depresses you most about the future?",
"what technological advancement do you wish you could see?",
"which country would you like to run?",
"when in your life have you felt most free?",
"given infinite resources, which population segment would you help first?",
"are there people in your life who you overlook? why?",
"when is the last time you knew you could have done better?",
"is there any pain in your body, right now?",
"what is your deepest shame?",
"is there anyone in your life you should apologise to but can’t?",
"when is the last time you said sorry and meant it?",
"what makes a sincere apology?",
"what is love?",
"what is time?",
"what is your favourite texture?",
"what is the most hopeful you have ever felt?",
"when is the last time you felt inspired?",
"when is the last time you sang?",
"when is the last time you gave a standing ovation?",
"who were you with last time you felt at peace?",
"what were you up to this time three Sundays ago?",
"what do you wish you had quit in your life?",
"what childhood skill do you wish you had stuck at?",
"when was the last time you felt proud of yourself? what had you done?",
"when was the last time someone congratulated you? how did it make you feel?",
"what law of physics would you alter if possible?",
"are there any social conventions that you wish you didn’t have to follow?",
"when is the last time you gave up?",
"do you respond to peer pressure? why/why not?",
"who do you talk to inside your head?",
"who was your first best friend?",
"if you could switch one living person (known to you) with one dead person, would you? who?",
"what is your favourite fact about humans?",
"what is your favourite fact about the universe?",
"what is your favourite historical fact?",
"do you believe in love at first sight?",
"what do you believe in spite of yourself?",
"are there any core traits that you have purely because you rebelled?",
"have you ever rebelled? when?",
"how do you remind yourself of your parents?",
"how do you wish you were more like your parents?",
"is there ever a time that you were honest but regretted it?",
"what is your favourite place in the world?",
"where do you hide?",
"have you ever betrayed anyone?",
"what super power would you like to have?"
]

module.exports = questions
